platform:
  - x64
environment:
  matrix:
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32
      TARGET: sbcl
      TARGETARCH: x86
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      TARGET: sbcl
      TARGETARCH: x86-64

install:

build_script:
  - choco install openssl.light
  - mkdir %HOMEDRIVE%%HOMEPATH%\.roswell\local-projects
  - git clone https://github.com/snmsts/sn.github.git %HOMEDRIVE%%HOMEPATH%\.roswell\local-projects\sn.github
  - git clone -b uiop https://github.com/snmsts/cl-gists.git %HOMEDRIVE%%HOMEPATH%\.roswell\local-projects\cl-gists
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S zlib-devel"
  - set PATH=C:\msys64\mingw32\bin;%PATH%
  - set ROSWELL_INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\roswell
  - set PATH=%ROSWELL_INSTALL_DIR%;%PATH%
  - set CC=i686-w64-mingw32-gcc
  - appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/vk58iojwkgq51nw4/artifacts/Roswell-i686.zip
  - 7z x -o%APPVEYOR_BUILD_FOLDER% Roswell-i686.zip

  - ros -s cffi-grovel -e "(setf cffi-grovel::*cpu-word-size-flags* '(\"-m32\"))" build.ros
test_script:
