platform:
  - x64
environment:
  matrix:
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

install:

build_script:
  - set ROSWELL_INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\roswell
  - set PATH=%ROSWELL_INSTALL_DIR%;%PATH%
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S zlib-devel"
  - appveyor DownloadFile https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.PS1
  - ps: install-for-ci.PS1
  
test_script:
  - ros build.ros
