platform:
  - x64
environment:
  global:
    MSYS2_BASEVER: 20150916
  matrix:
    - MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32
      TARGET: sbcl
      TARGETARCH: x86
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      TARGET: sbcl
      TARGETARCH: x86-64

install:
  - ps: If  (Test-Path ("msys" + $env:MSYS2_BITS)){Write-Host "Using cached msys2"}
  - ps: If (!(Test-Path ("msys" + $env:MSYS2_BITS))){Invoke-WebRequest -UserAgent wget -Uri ("http://kent.dl.sourceforge.net/project/msys2/Base/" + $env:MSYS2_ARCH +  "/msys2-base-" + $env:MSYS2_ARCH + "-" + $env:MSYS2_BASEVER + ".tar.xz") -OutFile "msys2.tar.xz"}
  - ps: If (!(Test-Path ("msys" + $env:MSYS2_BITS))){&"7z" x msys2.tar.xz}
  - ps: If (!(Test-Path ("msys" + $env:MSYS2_BITS))){&"7z" x msys2.tar > $nul;&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "";&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc ("for i in {1..3}; do pacman --noconfirm -Suy autoconf automake mingw-w64-"+ $env:MSYS2_ARCH + "-gcc make zlib-devel && break || sleep 15; done");&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "pacman --noconfirm -R -s bash-completion tftp-hpa inetutils util-linux tzcode time dash flex pax-git file bsdcpio bsdtar lndir";&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "yes|pacman --noconfirm -Sc";&("msys" + $env:MSYS2_BITS + "\autorebase.bat");}

build_script:
  - ps: &("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "pwd -W"
  - choco install openssl.light
  - mkdir %HOMEDRIVE%%HOMEPATH%\.roswell\local-projects
  - git clone https://github.com/snmsts/sn.github.git %HOMEDRIVE%%HOMEPATH%\.roswell\local-projects\sn.github
  - git clone https://github.com/Rudolph-Miller/cl-gists.git %HOMEDRIVE%%HOMEPATH%\.roswell\local-projects\cl-gists
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S zlib-devel"
  - set PATH=C:\msys64\mingw32\bin;%PATH%
  - set PATH=%APPVEYOR_BUILD_FOLDER%\roswell;%PATH%
  - set CC=i686-w64-mingw32-gcc
  - appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/9hrncgu1iofgxkbn/artifacts/Roswell-i686.zip
  - 7z x -o%APPVEYOR_BUILD_FOLDER% Roswell-i686.zip
  - ros list versions sbcl
  - ros -s cffi-grovel -e "(setf cffi-grovel::*cpu-word-size-flags* '(\"-m32\"))" build.ros

test_script:
