platform:
  - x64
environment:
  global:
    MSYS2_BASEVER: 20150916
  matrix:
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

install:
  - C:\msys64\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy autoconf automake mingw-w64-$MSYS2_ARCH-gcc make zlib-devel && break || sleep 15; done"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -R -s bash-completion tftp-hpa inetutils util-linux tzcode time rebase dash flex pax-git file bsdcpio bsdtar lndir"
  - C:\msys64\usr\bin\bash -lc "yes|pacman --noconfirm -Sc"
  - C:\msys64\autorebase.bat

build_script:
  - git clone -q --branch=release https://github.com/snmsts/roswell.git %APPVEYOR_BUILD_FOLDER%\roswell
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER;cd roswell; exec 0</dev/null; ./bootstrap; ./configure; make install"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER;ros build.ros"
  
test_script:
  - C:\msys64\usr\bin\bash -lc "mkdir /tmp;cd $APPVEYOR_BUILD_FOLDER;ros build.ros"
