platform:
  - x64
environment:
  matrix:
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

install:

build_script:
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S zlib-devel"
  - C:\msys64\usr\bin\bash -lc "where gcc"
  - set ROSWELL_INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\roswell
  - set PATH=%ROSWELL_INSTALL_DIR%;%PATH%
  - appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/vk58iojwkgq51nw4/artifacts/Roswell-i686.zip
  - 7z x -o%APPVEYOR_BUILD_FOLDER% Roswell-i686.zip
  - git clone https://github.com/snmsts/sn.github.git %APPVEYOR_BUILD_FOLDER%\sn.github
  - ros -l %APPVEYOR_BUILD_FOLDER%\sn.github\sn.github.asd build.ros
test_script:
