language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - LISP=sbcl-bin
  matrix:
    - TARGET=sbcl METHOD=ci TARGETARCH=x86
    - TARGET=sbcl METHOD=ci TARGETARCH=x86-64
os:
  - linux
  - osx

addons:
  apt:
    packages:
     - gcc-multilib
     - gcc-mingw-w64-i686
     - binutils-mingw-w64-i686
#     - wine
     - zlib1g-dev:i386

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew --env; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew config; fi

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - git clone https://github.com/snmsts/sn.github.git ~/lisp/sn.github

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - if [ "$METHOD" = "ci" ]; then ros version; fi
  - if [ "$METHOD" = "ci" ]; then ros version=t run; fi
  - if [ "$METHOD" = "ci" ]; then ros config; fi
  - ros build.ros
